### ISSUE TITLE
启动zhihufolloweepageprocessor后一直报编码的警告，没有内容被爬出来

### ISSUE THREAD

**Issue by xxiong95** [brianway/webporter#7]
WARN  us.codecraft.webmagic.downloader.HttpClientDownloader(HttpClientDownloader.java:198) ## Charset autodetect failed, use UTF-8 as charset. Please specify charset in Site.setCharset()

**Comment by brianway** [comment]
不太清楚你的运行环境。提示说你字符集没设置，设置一下就行了啊。而且这个是 webmagic 的警告，和 webporter 关系不大。
